### ISSUE TITLE
Could not load

### ISSUE THREAD

**Issue by TheChampTF** [FallenYouth/FlashlightPlus#4]
Running git-Bukkit-0899683 (MC: 1.8)

ERROR Could not load 'plugins/FlashlightPlus-1.0.8.jar' in folder 'plugins'

Full report http://paste.yu8.me/?8cbaf66b1ce66210#5kPrC1xgTxFtT4mT9Q5sNIH6aUnVeSysXhkG3qiwU0Y=

**Comment by FallenYouth** [comment]
I compiled it in Java 8. When I get home I could compile it in Java 7 if you'd like.

**Comment by TheChampTF** [comment]
Thanks, that would be helpful

**Comment by FallenYouth** [comment]
Get the FlashlightPlus.zip here: https://github.com/FallenYouth/FlashlightPlus/releases/tag/v1.0.8

This .zip contains a version compiled in 1.7 and 1.8 The one with the version number labeled 1.7-1.0.8 is the one for Java 7, it should work let me know if you have any issues.

**Comment by TheChampTF** [comment]
Looks like it did the trick, thx

**Comment by FallenYouth** [comment]
Alright cool. If you find that you think the plugin needs something added or needs something changed make a ticket and I'll get back to you.

Enjoy!
